[package]
name = "zero2prod"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "zero2prod"

[dependencies]
actix-web = "4"
tokio = { version = "1.48.0", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
sqlx = { version = "0.8.6", default-features = false, features = ["runtime-tokio-rustls", "macros", "postgres", "uuid", "chrono", "migrate"] }
config = "0.15.19"
uuid = { version = "1.19.0", features = ["v4"] }
chrono = { version = "0.4.42", default-features = false, features = ["clock"] }
tracing = { version = "0.1.44", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
tracing-bunyan-formatter = "0.3"
tracing-actix-web = "0.7"
tracing-log = "0.2"
secrecy = { version = "0.8", features = ["serde"] }


[dev-dependencies]
reqwest = "0.12.28"
